on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'
env:
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-BAR-2-1-chocolatine-eduardo.window.git"
  EXECUTABLES: "mysh,directory1/executableA"
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run coding style check
        run: bash check.sh $(pwd) $(pwd)

      - name: Annotate coding style errors
        if: always()
        run: |
          if [ -f coding-style-reports.log ]; then
            while IFS= read -r line; do
              # Assuming the log file contains lines in the format: "file:line: error message"
              file=$(echo "$line" | cut -d':' -f1)
              line_number=$(echo "$line" | cut -d':' -f2)
              message=$(echo "$line" | cut -d':' -f3-)
              echo "::error file=$file,line=$line_number::$message"
            done < coding-style-reports.log
          else
            echo "No coding style report found."
          fi

      - name: Fail job if errors found
        run: |
          if [ -s coding-style-reports.log ]; then
            echo "Coding style errors found. Failing the job."
            exit 1
          fi