on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'
env:
  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-BAR-2-1-chocolatine-eduardo.window.git"
  EXECUTABLES: "mysh,directory1/executableA"
jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run coding style check
        run: bash check.sh $(pwd) $(pwd)

      - name: Upload coding style report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coding-style-reports.log
          path: coding-style-reports.log

      - name: Annotate coding style errors
        if: failure()
        run: |
          while IFS= read -r line; do
            echo "::error file=${{ github.workspace }}/$line::Coding style error"
          done < coding-style-reports.log

      - name: Fail job if errors found
        if: failure()
        run: exit 1